### PR TITLE
fixes #164 - HDF5 backend won't compile with HDF5 >= 1.10.0

### LINKED ISSUE #164: ior-3.2.1 won't compile with -DHAVE_H5PSET_ALL_COLL_METADATA_OPS
In 3.2.1, autoconf will enable `HAVE_H5PSET_ALL_COLL_METADATA_OPS` if available which results in the following error:

```
aiori-HDF5.c(232): error: struct "<unnamed>" has no field "collective_md"
          if (param->collective_md) {
                     ^

compilation aborted for aiori-HDF5.c (code 2)
make[3]: *** [Makefile:1775: mdtest-aiori-HDF5.o] Error 2
```

because `param->collective_md` does not (and should not) exist in the 3.2 release.

The issue is that Rob Latham's collective metadata code wasn't fully backed out of the 3.2 tree before the release.  This can be fixed by just scrubbing the 3.2 branch for all remaining instances of `HAVE_H5PSET_ALL_COLL_METADATA_OPS` and re-releasing.  Should require no change on 3.3 and future releases.

### PR DESCRIPTION
**Pull request by glennklockwood**
Fixes #164.  Was easier than I thought.

### CODE REVIEW

**Comment by ax3l** [comment]
@glennklockwood can you rebase this PR against the latest CI updates?

**Comment by glennklockwood** [comment]
I cherry-picked 18f165f into this fix branch, `rc`, and `3.2`.  Thanks for the reminder.

**Comment by JulianKunkel** [comment]
The current IOR version compiles with HDF5-1.10.4. I believe the issue is closed.
