### PR TITLE
Feature: md-workbench

### PR DESCRIPTION
**Pull request by JulianKunkel**
This patchseries integrates the md-workbench benchmark into this benchmark test suite by porting the object-based API to AIORI and converting other bits and pieces as needed.
The plan is to transform a few more pieces of the code using IOR typical code and then to convert the tool to an API similar to MDTest and IOR.

The MD-Workbench differs from MDTest by providing means to benchmark performance of interactive users that do different operations.

Here is a paper about it:
https://hps.vi4io.org/_media/research/publications/2019/dlumlwmkm19-understanding_metadata_latency_with_mdworkbench.pdf

### CODE REVIEW

**Comment by glennklockwood** [comment]
I'm not sure this is specific to this md-workbench, but IOR now fails to compile on macOS 11.15 with Apple clang version 12.0.0 (clang-1200.0.32.21).  I haven't looked deeply at this, but if you see any quick fixes @JulianKunkel I figure I'd let you know sooner rather than later.

More feedback coming...

```
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in .
  CC       libaiori_a-md-workbench.o
md-workbench.c:147:13: error: static declaration of 'wait' follows non-static declaration
static void wait(double runtime){
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/wait.h:248:9: note: previous declaration is here
pid_t   wait(int *) __DARWIN_ALIAS_C(wait);
        ^
md-workbench.c:564:9: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *' [-Wint-conversion]
        FAIL("Unable to open file %s", obj_name);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./aiori-debug.h:12:37: note: expanded from macro 'FAIL'
#define FAIL(...) FailMessage(rank, ERROR_LOCATION, __VA_ARGS__)
                                    ^~~~~~~~~~~~~~
./utilities.h:38:24: note: expanded from macro 'ERROR_LOCATION'
#define ERROR_LOCATION __LINE__
                       ^~~~~~~~
<scratch space>:16:1: note: expanded from here
564
^~~
./aiori-debug.h:13:40: note: passing argument to parameter 'location' here
void FailMessage(int rank, const char *location, char *format, ...);
                                       ^
md-workbench.c:620:14: error: passing 'double' to parameter of incompatible type 'int *'
        wait(op_time);
             ^~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/wait.h:248:19: note: passing argument to parameter here
pid_t   wait(int *) __DARWIN_ALIAS_C(wait);
                  ^
md-workbench.c:642:9: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *' [-Wint-conversion]
        FAIL("Unable to open file %s", obj_name);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./aiori-debug.h:12:37: note: expanded from macro 'FAIL'
#define FAIL(...) FailMessage(rank, ERROR_LOCATION, __VA_ARGS__)
                                    ^~~~~~~~~~~~~~
./utilities.h:38:24: note: expanded from macro 'ERROR_LOCATION'
#define ERROR_LOCATION __LINE__
                       ^~~~~~~~
<scratch space>:21:1: note: expanded from here
642
^~~
./aiori-debug.h:13:40: note: passing argument to parameter 'location' here
void FailMessage(int rank, const char *location, char *format, ...);
                                       ^
md-workbench.c:654:14: error: passing 'double' to parameter of incompatible type 'int *'
        wait(op_time);
             ^~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/wait.h:248:19: note: passing argument to parameter here
pid_t   wait(int *) __DARWIN_ALIAS_C(wait);
                  ^
md-workbench.c:664:14: error: passing 'double' to parameter of incompatible type 'int *'
        wait(op_time);
             ^~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/wait.h:248:19: note: passing argument to parameter here
pid_t   wait(int *) __DARWIN_ALIAS_C(wait);
                  ^
md-workbench.c:678:9: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *' [-Wint-conversion]
        FAIL("Unable to open file %s", obj_name);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./aiori-debug.h:12:37: note: expanded from macro 'FAIL'
#define FAIL(...) FailMessage(rank, ERROR_LOCATION, __VA_ARGS__)
                                    ^~~~~~~~~~~~~~
./utilities.h:38:24: note: expanded from macro 'ERROR_LOCATION'
#define ERROR_LOCATION __LINE__
                       ^~~~~~~~
<scratch space>:24:1: note: expanded from here
678
^~~
./aiori-debug.h:13:40: note: passing argument to parameter 'location' here
void FailMessage(int rank, const char *location, char *format, ...);
                                       ^
md-workbench.c:692:14: error: passing 'double' to parameter of incompatible type 'int *'
        wait(op_time);
             ^~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/wait.h:248:19: note: passing argument to parameter here
pid_t   wait(int *) __DARWIN_ALIAS_C(wait);
                  ^
3 warnings and 5 errors generated.
make[3]: *** [libaiori_a-md-workbench.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

**Comment by JulianKunkel** [comment]
Okay, I renamed the wait symbol. Please try. The others might be follow up
errors.

**Comment by glennklockwood** [comment]
Thanks!  That did allow compilation to complete with a warning which I can worry about later.

```
aiori-POSIX.c:620:5: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *' [-Wint-conversion]
    FAIL("Error executing the sync command, ensure it exists.");
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./aiori-debug.h:12:37: note: expanded from macro 'FAIL'
#define FAIL(...) FailMessage(rank, ERROR_LOCATION, __VA_ARGS__)
                                    ^~~~~~~~~~~~~~
./utilities.h:38:24: note: expanded from macro 'ERROR_LOCATION'
#define ERROR_LOCATION __LINE__
                       ^~~~~~~~
<scratch space>:114:1: note: expanded from here
620
^~~
./aiori-debug.h:13:40: note: passing argument to parameter 'location' here
void FailMessage(int rank, const char *location, char *format, ...);
                                       ^
1 warning generated.
  CCLD     md-workbench
Making all in test
make[3]: Nothing to be done for `all'.
Making all in doc
make[1]: Nothing to be done for `all'.
Making all in contrib
  CC       cbif.o
  CCLD     cbif
make[1]: Nothing to be done for `all-am'.
```

This did reveal another macOS compilation issue introduced by recent DAOS cleanup, but I'll open a separate issue for that.

I'll do some more quick tire kicking and get back.

File: src/parse_options.c [hunk 1]
```diff
@@ -433,6 +433,7 @@ option_help * createGlobalOptions(IOR_param_t * params){
     {'y', NULL,        "dualMount -- use dual mount points for a filesystem", OPTION_FLAG, 'd', & params->dualMount},
     {'Y', NULL,        "fsyncPerWrite -- perform sync operation after every write operation", OPTION_FLAG, 'd', & params->fsyncPerWrite},
     {'z', NULL,        "randomOffset -- access is to random, not sequential, offsets within a file", OPTION_FLAG, 'd', & params->randomOffset},
+    {0, "random-offset-seed",        "The seed for -z", OPTION_OPTIONAL_ARGUMENT, 'd', & params->randomSeed},
```
Comment (glennklockwood) [inline src/parse_options.c:436]: Is this a part of the md-workbench patch or is this something that got accidentally rolled into this PR?

Comment (JulianKunkel) [reply src/parse_options.c:436]: You are right, I used it for testing. It is the "random" patch that I cherry-picked for the random branch. Merge should be conflict-free and this extra option doesn't do anything if not set  (adds reproducibility if set).

**Review by glennklockwood — APPROVED** [review]
All looks reasonable to me!
